# Generated by Django 5.2.14 on 2026-05-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='analise_sentimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Análise de Sentimento'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False, verbose_name='Concluída'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descriçaõ da Tarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='feedback_professor',
            field=models.TextField(blank='True', null='True', verbose_name='Feedback Professor'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='score_polaridade',
            field=models.FloatField(default=0.0, verbose_name='Score de Polaridade'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo da Tarefa'),
        ),
    ]
