# Generated by Django 5.2.14 on 2026-06-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tarefa_analise_sentimento_tarefa_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Categoria de Box',
                'verbose_name_plural': 'Categorias de Boxes',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='feedback_professor',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback Professor'),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Box')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localizacao')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_produto', models.CharField(blank=True, max_length=120, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('feirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL, verbose_name='Feirante')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='todo.categoriabox', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=120, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('texto_recomendacao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('analise_sentimento', models.CharField(blank=True, max_length=80, null=True)),
                ('score_polaridade', models.FloatField(default=0.0)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='todo.box')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendacao',
                'verbose_name_plural': 'Recomendacoes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
